xenia-canary/game-patches

patches/584108A9.patch

Current patch makes the classic graphics have a noisy effect on them, this patch works differently and seems to remove the blur without any bad effects.
(the check near where I patch is also checking for the 0x4E cheat-ID for "vaseline-o-vision", seems 82136FA0 is some sort of "isCheatActive" function - that check is left intact so the cheat/debug option should still work)

bean: improved remove-blur patch & rename debug-menu patch

---

patches/534507D6 - SONIC THE HEDGEHOG.patch

- Disable Bloom - fixed the HUD disappearing randomly.
- Disable Shadows - fixed crashing during cutscenes.
_Pro tip: always test more than one stage._

Fixed issues with SONIC THE HEDGEHOG (2006) patches

---

patches/58410955 - Banjo Tooie.patch

I put together an improved 60FPS code mod with fixes for pacing and for cut-scene softlocks,Canary Mary racing vehicles fixes to make those races beatable,and a custom asm routine that changes to 30fps when showing demos and for Jiggywiggy Challenges to make the timer and movement work properly.
**A previous test of 60FPS showed me that I was able to get 88 out of 90 Jiggies then beat the game before I added the Canary Mary fix,so the game should be possible to get 100% in.**
In addition to that,I have added an HD player shadows code along with some cheats including an infinite Ice Keys cheat for easier access to Dragon Kazooie without needing to access data from B-K to get the key.
I have plans to try to get high-poly nest objects and best stairs LoD quality codes made as well by …

Banjo Tooie: 60FPS Enhancements+HQ shadows

---

patches/58410955 - Banjo Tooie.patch

Sorry,I had completely forgotten about finding and adding the washing machine mach speed fix.
The fix prevents washing machine Banjo from going mach speed when attacking while moving on 60fps.

Added mach speed Washing Machine fix

---

patches/5454082B - Red Dead Redemption (GOTY, Disc 1).patch
patches/5454082B - Red Dead Redemption (GOTY, Disc 2).patch
patches/5454082B - Red Dead Redemption (Original, NTSC).patch
patches/5454082B - Red Dead Redemption (Original, NTSC, TU9).patch

WIP. Need to find the offsets for GOTY and make sure they all work.
Sun flare occlusion patch is currently incomplete and isn't being published. Although the rays no longer cast, the flare sprite is still being drawn.
Since I have only been able to test the relative performance differences using my mobile Zen2, and since RDR is particularly CPU limited, I'd appreciate it if others could test the patches on their Intel CPUs and report back.

5454082B - New Patches and Cleanup

---

patches/5454082B - Red Dead Redemption (GOTY, Disc 1).patch.toml

Seems the sun flare effect can clip through buildings when playing with increased resolutions, this prevents the effect from rendering.
Played for a few hours with this and didn't see any noticeable artifacts, the code patched here should only be sunflare related hopefully. 
I only have the Disc 1 GOTY edition ripped right now, if anyone is able to port this to the other versions it'd be appreciated, otherwise I'll try seeing if I can get hold of Disc 2 to port it there soon.
E: ugh github editor added a bunch of indents that broke linter, force pushed a fix.

RDR: disable sun/lens flare

---

patches/415608AF - GoldenEye 007 Reloaded.patch.toml
patches/41560904 - Transformers-Rise of The Dark Spark.patch.toml
patches/43430830 - Lost Planet 3.patch.toml
patches/45410850 - Mirror's Edge.patch.toml
patches/454108EF - Bulletstorm.patch.toml
patches/45410916 - Alice Madness Returns.patch.toml
patches/4D53082D - Gears of War 2 (TU6).patch.toml
patches/4D53082D - Gears of War 2.patch.toml
patches/4D5308AB - Gears of War 3 (TU6).patch.toml
patches/4D5308AB - Gears of War 3.patch.toml
patches/4D530A26 - Gears of War Judgment (TU4).patch.toml
patches/5454082B - Red Dead Redemption (GOTY, Disc 1).patch.toml
patches/5454082B - Red Dead Redemption (GOTY, Disc 2).patch.toml
patches/5454082B - Red Dead Redemption (Original, NTSC).patch.toml
patches/5454082B - Red Dead Redemption (Original, NTSC, TU9).patch.toml
patches/5454085D - Bioshock Infinite.patch.toml
patches/565707D0 - Lollipop Chainsaw (Premium Edition).patch.toml
patches/565707D0 - Lollipop Chainsaw.patch.toml

- Updated UE3 hashes
- Add bloom  & dof patches for Gears; TU parity
- GoldenEye reloaded hash & 16x af
- RDR housekeeping (remove faulty ssao patch, add vsync disclaimer, remove old no-intro, convert sun flare to all ver, reorganize patch order)

Hashes, Gears TUs, 16x AF, RDR Housekeeping

---

patches/45410850 - Mirror's Edge.patch.toml
patches/4D5307D5 - Gears of War (TU5).patch.toml
patches/4D5307D5 - Gears of War.patch.toml
patches/4D5707D7 - Blacksite.patch.toml
patches/4D5707DB - Unreal Tournament 3.patch.toml
patches/4D5707DF - TNA Impact (TU1).patch.toml
patches/4E4D080B - Magnacarta2.patch.toml
patches/5451083B - 50 Cent Blood on the Sand.patch.toml

The culprit behind the so-called "black shading" problem seems to be mostly caused by an issue Xenia has with UE3's tiled MSAA implementation. 
Forcing non-tiled MSAA eliminates all artifacts seen on characters and geometry within the boundaries of a light environment in Gears of War, Blacksite Area 51, Magnacarta 2, Mass Effect, and Unreal Tournament (2007).
For games that were made after SSAO was introduced to UDK, but before the Lightmass system was adopted that replaced lightmaps, the default int value of cvar `GMaxShadowDepthBufferSize` also needs to be increased (Gears of War 2, Dark Void).
This isn't necessarily a one size fits all approach. Mass Effect 2 and Mirror's Edge still exhibit the same significant shading issues with or w/o tiling. There are still a **_lot_** of …

UE3 Games 2006-2010: "Black Shading" Dynamic Lighting Artifacts

---

patches/53450812 - Sonic Unleashed (TU2).patch.toml
patches/53450812 - Sonic Unleashed.patch.toml

For some reason this patch was also a part of the `1280x720 Resolution` patch.
before:
after:

Separate Color Adjustment patch for Sonic Unleashed

---

patches/58410955 - Banjo-Tooie.patch.toml

I added a port of my recent Draw Distance Hack finding, it may have mild issues in WitchyWorld under extreme conditions such as using split-up and having Banjo stand on the diving board looking towards the world entrance with Kazooie in the same area and both Big Al's Burgers and Salty Joe's Fries activated.
A render freeze or some hitching can occur but no crashes or major glitches from that.
Later worlds not yet tested but hopefully they should fare better since WitchyWorld is nowhere near as bad as it acted on the N64 version of the code.

Update 58410955 - Banjo-Tooie.patch.toml

---

patches/58410955 - Banjo-Tooie.patch.toml

This allows you to use Breegull Bash without needing to do the cumbersome task of getting four SNS eggs in the first game before you can get the move in Tooie.
To note my experience with that task, I ran into trouble on Xenia before when trying to access the move with it not detecting the B-K eggs, yet Banjo N&B worked fine for detecting them being collected by revealing the special SNS Mumbo crates.

Add Breegull Bash cheat.

---

patches/4D5307ED - Banjo-Kazooie Nuts & Bolts.patch.toml
patches/58410955 - Banjo-Tooie.patch.toml

(3 commits listed but only 1 commit is what I want to have merged) Hope this works.
Max parts doesn't modify the actual owned parts count but it allows uncapped parts usage even after saving vehicles as long as the code is active. Want six Super Engines on a vehicle after getting one? No problem! (19 jets can be fun as well)
Ammo and Fuel Never Decrease cheat should be self-explanatory, allowing only needing smallest/lightest fuel and ammo for more broken vehicle building. Attempting to attach two ejector seat parts hangs the game, self destruct likely may also cause hanging with trying to add two or more.

B-K N&B Cheats for Max Parts Infinite Ammo and Fuel

---

patches/4D5307DF - ブルードラゴン.patch.toml

Adds Extra debug information to the game world such as event information and wireframe (can't be enabled using debug menu so patch is needed)

Update 4D5307DF - ブルードラゴン.patch.toml

---

patches/4D5307DF - Blue Dragon.patch.toml

Debug Menu figured out on english releases. Credits to [Drago](https://github.com/megadrago88) for helping
Features of this debug menu are a bit unstable but the folks at the [blue dragon speedrunning discord server](https://discord.gg/gqpBMVh9xP) are working on stablising these features

Update 4D5307DF - Blue Dragon.patch.toml

---

patches/4D5307D2 - Kameo Elements of Power (TU2).patch.toml
patches/4D5307D3 - Perfect Dark Zero (Platinum Hits).patch.toml
patches/4D5307D3 - Perfect Dark Zero (TU3).patch.toml
patches/4D53085F - Viva Piñata Trouble in Paradise (TU1).patch.toml

Adds codes for games with title updates like Kameo, Perfect Dark Zero, and Viva Piñata: Trouble in Paradise. The FPS patch for Perfect Dark Zero was also broken, but I fixed it and changed it to allow the game to run up to 60 FPS to be more in-line with other Rare games. (Besides, if anyone wanted to play at higher than 60 FPS, they could just disable VSync in settings).

Add TU patches for Kameo, PDZ and Viva Piñata

---

patches/545107FC - Saints Row 2 (TU1).patch.toml
patches/545107FC - Saints Row 2.patch.toml

Patch that forces the game to run at the highest resolution it can.

Saints Row 2 720p patch (Base + TU)

---

patches/545107FC - Saints Row 2 (TU1).patch.toml
patches/545107FC - Saints Row 2.patch.toml

Patches that let you disable effects that normally cannot be turned off in the game.

Saints Row 2 patches to disables various effects. (Base + TU)

---

patches/434D07E0 - Turning Point Fall of Liberty.patch.toml

This patch fixes the broken shadows in the game.

Fix broken shadows in Turning Point: Fall of Liberty

---

.github/Plugin-Docs.md
.github/README.md

Document the usage of plugins for [Xenia Canary](../../../../xenia-canary).

Plugin Documentation

---

patches/545107D1 - Saints Row (TU1).patch.toml
patches/545107FC - Saints Row 2 (TU3).patch.toml

A port of loose files loading & Havok physics fix from [Juiced Patch](https://kobraworks.com/), found by @scanti2 and @theuzis respectively 
Original file loading priority/hierarchy
`vdir->dlcs->vpps`
First patch changes it to
`raw->dlcs->vpps`
Alternative patch changes it to
`raw->vdir->dlcs->vpps`
vdir seems to be unused in Saints Row 1?
Havok fix consists of simply replacing the havok frametime value with (current frametime/2) in the main game loop

Load loose files for SR1 & Havok physics fix patch for 1&2

---

patches/545107D1 - Saints Row (TU1).patch.toml
patches/545107D1 - Saints Row.patch.toml

For Saints Row TU1:
- Edits current emoose's debug console patch to allow you to open / close the console window instead of only closing.
- Print debug_print LUA function to Xenia console / log with DbgPrint

Saints Row: Debug patches

---

patches/5345082B - Planet 51 The Game.patch.toml

Same sort of black shading fix that @bomabomaboma provided for a bunch of UE3 games in #169

Fix UE3 black shading in Planet 51: The Game

---

patches/41560817 - Call of Duty - Modern Warfare 2 (TU0).patch.toml
patches/41560817 - Call of Duty - Modern Warfare 2 (TU9).patch.toml
patches/41560817 - Call of Duty - Modern Warfare 2 MP (TU0).patch.toml
patches/41560817 - Call of Duty - Modern Warfare 2 MP (TU9).patch.toml

I have no idea why this works but it makes the game at least playable when using upscaling x2 or x3.
Before: **WARNING FLASHING VIDEO**
https://github.com/user-attachments/assets/9148ac0a-b488-4a42-acc0-387aa333e38d
After:
https://github.com/user-attachments/assets/0f86dfc3-d450-4ba3-8ac2-42db2a22517f

feat: add 41560817 MW2 patches for upscale flicker fix

---

patches/4D5307ED - Banjo-Kazooie Nuts & Bolts (TU3).patch.toml
patches/58410954 - Banjo-Kazooie (TU2).patch.toml

Ports over the newly-added patches for Banjo-Kazooie Nuts & Bolts by retroben to TU3.
I also added a template for Title Update 2 of Banjo-Kazooie with one code that already works, but I will NOT be porting the 60 FPS patch to TU2 since it uses ASM injection.

Update Banjo patches

---

patches/544307D1 - DEAD OR ALIVE 4.patch.toml

For base DOA 4. Helenas 'opera' and christie's costume are cinematics only and never meant to fight with, meaning those aren't unused unlike Kokoro's. Don't hesitate to rename my changes because English isn't my main language and cinematic-only seems clear albeit sounding a bit janky.

Update 544307D1 - DEAD OR ALIVE 4.patch.toml

---

patches/544307D1 - DEAD OR ALIVE 4 (Rev1).patch.toml

For REV1. Helenas 'opera' and christie's costume are cinematics only and never meant to fight with, meaning those aren't unused unlike Kokoro's. Don't hesitate to rename my changes because English isn't my main language and cinematic-only seems clear albeit sounding a bit janky.

Update 544307D1 - DEAD OR ALIVE 4 (Rev1).patch.toml
