patches/454108E6.patch
It does what it says on the tin. same as the rpcs3 patch.
=> added skate 3 no fall damage patch

patches/4B4E0823.patch
=> Add Silent Hill Downpour unlock FPS patch

patches/58410955 - Banjo Tooie.patch
This patch code is nice for those who love the jump sounds from the first game,a quick and easy port from known N64 values.
=> Added classic jump sounds code

patches/58410955 - Banjo Tooie.patch
Makes nests and their contents like musical notes look much nicer when at a distance away and makes the stairs leading to Targitzan in MT always full 3D.
The musical notes look very pretty with this when viewed from far away.
=> Added nests and stairs lod hack

patches/415608AF - Goldeneye 007 Reloaded.patch
WIP - leave open.
Investigating whether other Bond games have similar occlusion problems.
=> IW Lens Flares

patches/58410954 - Banjo Kazooie.patch
Not tested yet for a full run of the game but should hopefully work for the entire game.
Two things I couldn't figure out the full fix ports for are the jump gravity of the clams in TTC and the Sir Slush snowman's snowball throwing strength which don't completely break things so hopefully it should be fine.
=> Finished Banjo Kazooie 60fps mod codes

patches/53450812 - SONIC UNLEASHED (TU2).patch
=> Sonic Unleashed

patches/445007EA - Onechanbara.patch
First time doing this. Let me know if something needs to be changed/fixed. :fingers_crossed:
=> Cheats for Onechanbara.

patches/454108E6 - Skate 3.patch, patches/4D5307DF - Blue Dragon.patch, patches/4D53082D - Gears of War 2.patch, patches/4D5308AB - Gears of War 3.patch, patches/4D530A26 - Gears of War Judgment.patch, patches/58410954 - Banjo Kazooie.patch, patches/58410955 - Banjo Tooie.patch, patches/5841096A - Hydro Thunder Hurricane.patch, patches/584111F7 - Minecraft (XBLA, TU0).patch
=> Add missing hashes

patches/43430817 - Asura's Wrath.patch, patches/45410850 - Mirror's Edge.patch, patches/454108EF - Bulletstorm.patch, patches/4541092A - Shadows of the Damned.patch, patches/4B4E0823 - Silent Hill Downpour (TU1).patch, patches/4B4E0823 - Silent Hill Downpour.patch, patches/4D5307D5 - Gears of War (TU5).patch, patches/4D5307FA - Lost Odyssey (NTSC-J).patch, patches/4D53082D - Gears of War 2 (TU6).patch, patches/4D53082D - Gears of War 2.patch, patches/4D5308AB - Gears of War 3 (TU6).patch, patches/4D5308AB - Gears of War 3.patch, patches/4D530A26 - Gears of War Judgment.patch, patches/4D5707DB - Unreal Tournament 3.patch, patches/53450812 - SONIC UNLEASHED (TU2).patch, patches/53450812 - SONIC UNLEASHED.patch, patches/5451083B - 50 Cent Blood on the Sand.patch, patches/5454085D - Bioshock Infinite.patch, patches/565707D0 - Lollipop Chainsaw Premium Edition.patch, patches/565707D0 - Lollipop Chainsaw.patch
- Add present_interval component to existing UE3 patches, and create several new ones for games w/o smoothframerate
- Update NTSC-J Lost Odyssey
- Update several desc
- Update existing TU files up to parity with their base ver counterparts.
- Redo patch order for UE3 games based on estimated relevance.
- Add Gears of War TU5
- Add Sonic Unleashed present_interval 60 FPS
=> UE3 Update

patches/54510850 - SpongeBob - Truth or Square.patch
Fixes FMVs freezing on playback.
=> Add Gliniak's SpongeBob: Truth-Sq. patch

patches/4541092A - Shadows of the Damned.toml, patches/4D5707DB - Unreal Tournament 3.toml, patches/584108F6 - Shadow Complex.toml
Before I go radio silent for a couple weeks I decided to systematically vet all of the patches I've created. I noticed two small offset errors from my last big merge of UE3 patches.
I'm also adding some patches for XBLA title Shadow Complex that I created ages ago.
=> SotD/UT3: address corrections

.github/README.md
Add note about multiple hashes.
Update Blue Dragon example patch.
Add notes about ESLint and VSCode.
Revise obtaining xex hash.
=> README improvements

.eslintrc.js
=> Only allow one newline at end of file

patches/5454082B - Red Dead Redemption (GOTY, Disc 1).toml, patches/5454082B - Red Dead Redemption (GOTY, Disc 2).toml, patches/5454082B - Red Dead Redemption (Original, NTSC).toml, patches/5454082B - Red Dead Redemption (Original, NTSC, TU9).toml
-Renames
-Add 360p and 540p modes
-Convert bottomless clip for GOTY and TU9
=> RDR - small changes

patches/545407F8 - Midnight Club Los Angeles Complete Edition.toml
No uppercase addrs :goose_knife:
=> MCLA: Disable motion blur patch

patches/545407F2 - Grand Theft Auto IV.toml
=> Add GTA IV Skip Legal patch

patches/445007EA - Onechanbara.patch.toml
Adding module name, for reasons.
=> Update 445007EA - Onechanbara.patch.toml

patches/545107D1 - Saints Row (TU1).patch.toml, patches/545107D1 - Saints Row.patch.toml
A hacky patch for enabling r_ugly_mode. Might be broken for someone. Needs some testing.
=> Add a patch for enabling r_ugly_mode in Saints Row

patches/475807D1 - Lucha Libre AAA Heroes del Ring.patch.toml, patches/4D5307FA - Lost Odyssey (NTSC-J).patch.toml, patches/545107FE - DAH Path of the Furon.patch.toml, patches/565507D4 - The Bourne Conspiracy.patch.toml, patches/584108F6 - Shadow Complex.patch.toml
Destroy All Humans - Path of the Furon: unlock FPS, ppx, 16x AF
Bourne Conspiracy: unlock FPS, blur, DoF, 16x AF
Lost Odyssey (Japan) - New hash, mediaid, redump link
Shadow Complex - New hash
=> Odds and ends

patches/58410955 - Banjo-Tooie.patch.toml
Hopefully there is no major issues this time with problematic areas using reduced draw distance caps.
Unfortunately means a trade-off but at least much less chance of rendering freezes.
=> Banjo Tooie Draw Distance code revised,

patches/4D5307DF - ブルードラゴン.patch.toml
=> Debug Menu For Blue Dragon

Naruto Rise of a Ninja Widescreen, patches/555307E5 - Naruto Rise of a Ninja.patch.toml
21:9 Widescreen patch for the game.
=> Naruto Rise of a Ninja Widescreen

patches/4D5307DF - ブルードラゴン.patch.toml
=> Fix To ブルードラゴン

.github/README.md
An array is patched using a string.
=> [README] Fixed array value

patches/545407EE - The Darkness.patch.toml
This can be added back now since it gets ingame.
Related: #181
=> Add back The Darkness

patches/4D5307DF - Blue Dragon.patch.toml
Wylie has found a few additional debug tools in the Blue Dragon Debug Menu but have never been committed here
=> Add Wylie's additional debug menu findings

.github/README.md
This is needed because some people think Xbox 360(!!!) games are a couple kilobytes.
=> Disclaimer for idiots

patches/584111F7 - Minecraft (XBLA, TU1).patch.toml, patches/584111F7 - Minecraft (XBLA, TU2).patch.toml, patches/584111F7 - Minecraft (XBLA, TU3).patch.toml, patches/584111F7 - Minecraft (XBLA, TU4).patch.toml
Ported debug menu patch to TU1, TU2, TU3, TU4
=> Minecraft Debug Menu

patches/58410A8D - Dead Rising 2 Case Zero.patch.toml
Unlocked FPS, Enabled Developer Settings and Intro Logo Skip.
=> Create 58410A8D - Dead Rising 2 Case Zero.patch.toml

patches/445007F4 - お姉チャンバラZ～カグラ～.patch.toml
Invincibility with kagura's dual daggers and No Splatter Gauge
=> Create 445007F4 - Onechanbara Z Kagura patch

patches/545107D1 - Saints Row.patch.toml
Backport of the 1.0.1 (TU1) patches to 1.0
=> Update 545107D1 - Saints Row.patch.toml

patches/53510806 - Final Fantasy XIII-2.patch.toml
See issue https://github.com/xenia-canary/game-patches/pull/302.
=> Final Fantasy XIII-2: Fix link to debug menu font

patches/465307D7 - Tenchu Z.patch.toml
Tenchu Z 60 FPS patch, Cutscene 2X Speed
=> Create 465307D7 - Tenchu Z.patch.toml

patches/4156082F - Marvel Ultimate Alliance 2.patch.toml
This game has been out for 14 years and there is no patch for it?
=> Marvel Ultimate Alliance 2: Cheat Patches

patches/4D5307FA - Lost Odyssey.patch.toml
=> Lost Odyssey Edit Menu

patches/415607E1 - Call Of Duty 3 (TU3).patch.toml, patches/415607E1 - Call Of Duty 3 MP (TU0).patch.toml, patches/415607E1 - Call Of Duty 3 MP (TU3).patch.toml, patches/415607E1 - Call Of Duty 3 MP.patch.toml, patches/415607E1 - Call Of Duty 3.patch.toml
Mostly patches that fixes graphical artifacts with the game
[Grass Before](https://github.com/user-attachments/assets/d4b3d72b-1545-471d-ac2f-6abae8cd562a)
[Grass After](https://github.com/user-attachments/assets/1de35dfe-6576-44bd-b9ac-0f92e9cd7a5d)
=> Call Of Duty 3 patches

patches/434107D2 - Tetris The Grand Master Ace.patch.toml
patch to unlock all the offline gamemodes even if your save was never connected to the Xbox Live.
=> TGM ACE - Unlock All Gamemodes

patches/545107D1 - Saints Row (TU1).patch.toml, patches/545107FC - Saints Row 2 (TU3).patch.toml
Some patches by @Tervel1337 and me for both games on latest version.
also renamed
`545107FC - Saints Row 2 (TU1).patch.toml` 
to 
`545107FC - Saints Row 2 (TU3).patch.toml`
=> SR1 & 2 patches 

.gitattributes
Fixes b6932f478713cbfeac7890cec3afb893f85df957
=> Enforce lf on patch files

patches/555307EE - Import Tuner Challange.patch.toml
Finally added it to repository, so there is no need to look for it on discord/YT
=> Import Tuner Challange - Blackscreen patch

patches/53450848 - Sonic Generations.patch.toml
Added a 60 fps patch for Sonic Generations. Done having used the previously existing work by boma for Sonic Unleashed and Xbox 360 Forever's instructions for Sonic Unleashed and Sonic Generations, therefore, they are included in the credits. Tested this new patch and it totally works, players can now enjoy Sonic Generations in 60 fps.
=> Create 53450848 - Sonic Generations.patch.toml

patches/454107D9 - Need for Speed Most Wanted (2005).patch.toml
The patch has been tested and it's working on this disc region too.
=> Add support for NFS:Most Wanted [PAL-ITA] Disc

patches/53450848 - Sonic Generations (TU2).patch.toml
60 FPS patch for Title Update 2
=> Create 53450848 - Sonic Generations (TU2).patch.toml

patches/434307E0 - Dark Void (TU1).patch.toml, patches/434307E0 - Dark Void.patch.toml, patches/434D07DE - Rise of the Argonauts.patch.toml, patches/475007D3 - Legendary.patch.toml, patches/4B4E0802 - Saw.patch.toml, patches/4B4F07D7 - Fatal Inertia (TU1).patch.toml, patches/4B4F07D7 - Fatal Inertia.patch.toml, patches/5343080B - Batman Arkham Asylum GOTY.patch.toml, patches/535107DA - The Last Remnant.patch.toml, patches/58410873 - Undertow (TU2).patch.toml, patches/58410873 - Undertow.patch.toml, patches/58410921 - CellFactor PW.patch.toml, patches/58410964 - Alien Breed Episode 1.patch.toml, patches/58410A22 - Alien Breed 2 Assault.patch.toml, patches/58410AA3 - Alien Breed 3 Descent.patch.toml
Thanks to HouseofTudor and Boma for making it easy.
=> MSAA tiling patches

patches/415607E6 - Call of Duty 4 Modern Warfare (TU4).patch.toml, patches/415607E6 - Call of Duty 4 Modern Warfare MP (TU4).patch.toml
Before:
https://github.com/user-attachments/assets/00bd1e24-2032-4ea8-b7b2-bc623ebc3cfd
After:
https://github.com/user-attachments/assets/3a789f08-88b1-4b3d-856f-e13e8b7917af
=> feat: add 415607E6 COD4 patches for upscale flicker fix

patches/544307D1 - DEAD OR ALIVE 4 (TU1).patch.toml
=> Update 544307D1 - DEAD OR ALIVE 4 (TU1).patch.toml

patches/544307D1 - DEAD OR ALIVE 4 (Rev1).patch.toml
=> Update 544307D1 - DEAD OR ALIVE 4 (Rev1).patch.toml
